esphome:
  name: wohnzimmer
  friendly_name: Wohnzimmer
  comment: Wohnzimmer Steuereinheit & Sensorik
  project: 
    name: "Dominic Hahn.wohnzimmer"
    version: "2.1.0"
###############################
esp8266:
  board: esp01_1m
##########################
logger:
##############################
api:
  encryption:
    key: "Ahj7+FcUBss5qngsvFNv6qMgTB7gtkIUg7uWc/rCrZY="
##############################
ota:
  - platform: esphome
    password: "e4dd1682c7eedf827ec2793b7f9b49a5"
####################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.180
    gateway: 192.168.1.1
    dns1: 192.168.1.4
    subnet: 255.255.255.0
#############################
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    internal: True
    id: wifi_signal_db
    update_interval: 10s

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: template
    name: "RGB Verbrauch"
    id: led_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    update_interval: 1s
    lambda: |-
      if (id(rgb_leds).current_values.is_on()) {
        float brightness = id(rgb_leds).current_values.get_brightness();  // 0.0 - 1.0
        return brightness * 12.0;  // 12 W @ 100%
      } else {
        return 0.0;
      }
############################
switch:
  - platform: gpio
    name: "Wohnzimmer-PC"
    pin: GPIO12
    device_class: outlet
    icon: "mdi:desktop-tower-monitor"
#########################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: false
    name: "Balkon"
    device_class: door
#########################
output:
  - platform: gpio
    pin: GPIO5
    id: white
    inverted: true

  - platform: gpio
    pin: GPIO16
    id: led_builtin
    inverted: true


light:
  - platform: binary
    output: white
    name: Warm White
    icon: "mdi:led-strip-variant"


  - platform: neopixelbus
    type: RGB
    pin: GPIO15
    icon: "mdi:television"
    id: rgb_leds
    num_leds: 16
    name: "Ambiente"
    variant: WS2811
    effects:
      - random:
          name: "Random Mood"
          transition_length: 1s
          update_interval: 2s
      - flicker:
          name: "Candle Flicker"
          alpha: 95%
          intensity: 3.5%
      - addressable_rainbow:
          name: "Rainbow Flow"
          speed: 8
          width: 80
      - addressable_twinkle:
          name: "Galaxy Twinkle"
          twinkle_probability: 10%
          progress_interval: 6ms
      - addressable_color_wipe:
          name: "Alarm Rot"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Grün"
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Blau"
          colors:
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true


      - addressable_lambda:
          name: "Minecraft"
          update_interval: 100ms
          lambda: |-
            for (int i = 0; i < 16; i++) {
              if (i < 4) {
                // 1–3 braun
                it[i] = Color(181, 101, 29);
              } else if (i < 12) {
                // 4–12 grün
                it[i] = Color(0, 255, 0);
              } else {
                // 13–16 braun
                it[i] = Color(181, 101, 29);
              }
            }




web_server:
  version: 3
  port: 80



