esphome:
  name: esp-schlafzimmer
  friendly_name: ESP Schlafzimmer
  comment: ESP8266 in YeeLight Bedside Lamp 2
  project: 
    name: "Dominic Hahn.schlafzimmer"
    version: "2.1.1"

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: "P5k3q3GR5NYMHN0lyW1zBA7gWEoG7u4BKHZKIrAw+e8="

ota:
  - platform: esphome
    password: "1421d99370157aae85e923d20e23c9ac"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2
  manual_ip:
    static_ip: 192.168.1.102
    gateway: 192.168.1.1
    subnet: 255.255.255.0

output:
  - platform: gpio
    pin: 14
    inverted: False
    id: purple_led

web_server:
  port: 80
  version: 3

i2c:
  sda: GPIO4
  scl: GPIO5
  scan: true

binary_sensor:
  - platform: gpio
    icon: "mdi:sleep"
    pin:
      number: 13
      mode: 
        input: True
        pullup: True
    name: "Bed Switch"

light:
  - platform: binary
    name: "Nachttisch"
    output: purple_led
    icon: "mdi:buffet"
    id: lampe

  - platform: neopixelbus
    type: RGB
    pin: GPIO12
    icon: "mdi:bed"
    num_leds: 25
    id: bett_leds
    name: "Bett"
    variant: WS2811
    effects:
      - random:
          name: "Random Mood"
          transition_length: 1s
          update_interval: 2s
      - flicker:
          name: "Candle Flicker"
          alpha: 95%
          intensity: 3.5%
      - addressable_rainbow:
          name: "Rainbow Flow"
          speed: 8
          width: 80
      - addressable_twinkle:
          name: "Galaxy Twinkle"
          twinkle_probability: 10%
          progress_interval: 6ms
      - addressable_color_wipe:
          name: "Alarm Rot"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 25
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 25
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Gr√ºn"
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 25
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 25
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Blau"
          colors:
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 25
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 25
          add_led_interval: 50ms
          reverse: true

sensor:
  - platform: bme280_i2c
    temperature:
      name: "Raumtemperatur"
      oversampling: 4x
    humidity:
      name: "Luftfeuchtigkeit"
    address: 0x76
    update_interval: 10s

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    internal: True
    id: wifi_signal_db
    update_interval: 10s

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

  - platform: template
    name: "Bett LED Stripe"
    id: led_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    update_interval: 1s
    lambda: |-
      if (id(bett_leds).current_values.is_on()) {
        float brightness = id(bett_leds).current_values.get_brightness();
        return brightness * 12.0;
      } else {
        return 0.0;
      }

