esphome:
  name: esp-wohnzimmer
  friendly_name: ESP Wohnzimmer
  comment: Wohnzimmer Steuereinheit & Sensorik
  project: 
    name: "Dominic Hahn.wohnzimmer"
    version: "2.1.0"
###############################
esp8266:
  board: esp01_1m
##########################
logger:
##############################
api:
  encryption:
    key: "Ahj7+FcUBss5qngsvFNv6qMgTB7gtkIUg7uWc/rCrZY="
##############################
ota:
  - platform: esphome
    password: "e4dd1682c7eedf827ec2793b7f9b49a5"
####################################
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2
  manual_ip:
    static_ip: 192.168.1.180
    gateway: 192.168.1.1
    dns1: 192.168.1.4
    subnet: 255.255.255.0
#############################
sensor:
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    internal: True
    id: wifi_signal_db
    update_interval: 60s
#____________________________________________#
  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
#########################
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: false
    name: "Balkon"
    device_class: door
#########################
output:
  - platform: gpio
    pin: GPIO5
    id: white
    inverted: true
#######################################
light:
  - platform: binary
    output: white
    name: Warm White
    id: warm_white
    icon: "mdi:television"
#____________________________________________#
  - platform: neopixelbus
    type: RGB
    pin: GPIO15
    icon: "mdi:television"
    id: rgb_leds
    num_leds: 16
    name: "LED Stripe"
    variant: WS2811
    effects:
      - addressable_color_wipe:
          name: "Alarm Rot"
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Grün"
          colors:
            - red: 0%
              green: 100%
              blue: 0%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true
      - addressable_color_wipe:
          name: "Alarm Blau"
          colors:
            - red: 0%
              green: 0%
              blue: 100%
              num_leds: 16
            - red: 0%
              green: 0%
              blue: 0%
              num_leds: 16
          add_led_interval: 50ms
          reverse: true
      - addressable_lambda:
          name: "Minecraft"
          update_interval: 100ms
          lambda: |-
            for (int i = 0; i < 16; i++) {
              if (i < 4) {
                // 1–3 braun
                it[i] = Color(181, 101, 29);
              } else if (i < 12) {
                // 4–12 grün
                it[i] = Color(0, 255, 0);
              } else {
                // 13–16 braun
                it[i] = Color(181, 101, 29);
              }
            }